- C++/Data_Structures/Segment_Tree_Sum.cpp
> Added Segment Tree for sum!

- CodeForces Problems/1560-C.cpp
Please review the solution for the problem 1560 C. 
here's the link for the question : [Question](https://codeforces.com/contest/1560/problem/C)
here's the link for the question : [Solution](https://codeforces.com/contest/1560/submission/126352908l)
> Added problem solution 1560 C

- CodeForces Problems/1559-C.cpp
Please review the solution for the problem 1559 C. 
here's the link for the question : [Question](https://codeforces.com/contest/1560/problem/C)
here's the link for the question : [Solution](https://codeforces.com/contest/1559/submission/126049036)
> Added problem 1559 C

- CodeForces Problems/1560-B.cpp
Please review the solution for the problem 1559 C. 
here's the link for the question : [Question](https://codeforces.com/contest/1560/problem/B)
here's the link for the question : [Solution](https://codeforces.com/contest/1560/submission/126316432)
> Added problem 1560 B

- .vscode/settings.json
- CodeForces Problems/1560-A.cpp
Please review the solution for the problem 1559 C. 
here's the link for the question : [Question](https://codeforces.com/contest/1560/problem/A)
here's the link for the question : [Solution](https://codeforces.com/contest/1560/submission/126279587)
> Added problem 1560 A

- CodeForces Problems/407-A.cpp
A ladder question of CF contest 239 DIV 1
Question : [Ques](https://codeforces.com/contest/407/problem/A)
Solution : [Ans](https://codeforces.com/contest/407/submission/130252539)
> Add sol for 407 A

- CodeForces Problems/1581-B.cpp
- CodeForces Problems/242-C.cpp
C ladder question of CF contest Solution 149 DIV 2
Question : [Ques](https://codeforces.com/contest/242/problem/C)
Solution : [Ans](https://codeforces.com/contest/242/submission/130289525)
> Cf 242 C Solution

- CodeForces Problems/1581-B.cpp
B ladder question of CF contest 745 DIV 2
Question : [Ques](https://codeforces.com/contest/1581/problem/B)
Solution : [Ans](https://codeforces.com/contest/1581/submission/130440125)
> Add sol for 1581 B

- LeetCode Problems/C#/36. Valid Sudoku/README.md
- LeetCode Problems/C#/36. Valid Sudoku/Solution.cs
> C# solution for Leetcode problem 36. Valid Sudoku

- CodeForces Problems/1581-A.cpp
Question : [Ques](https://codeforces.com/contest/1581/problem/A)
Solution : [Ans](https://codeforces.com/contest/1581/submission/130440511)
> Add 1581 A Sol

- C++/Recursion/josephus_problem_lucky_number.cpp
- C++/Recursion/max_cut_of_rope.cpp
- C++/Recursion/palindrome.cpp
- C++/Recursion/subarray_substring.cpp
- C++/Recursion/sum_of_digi.cpp
In recursion added 5 problems regarding it .
lucky number problem:
Deleting index wise elements in array and the one that left at last is a lucky number
max_cut_of_rope
palindrome or not
all substrings of a string
sum of digits of number
> Added a new folder inside cpp for recursion

- C++/Data_Structures/sorting/bubble_sort.cpp
- C++/Data_Structures/sorting/insertion_sort.cpp
- C++/Data_Structures/sorting/quick_sort.cpp
- C++/Data_Structures/sorting/selection_sort.cpp
hi there,
I'm adding 4 sorting techniques. Kindly merge it.
> added sorting techniques

- UI/login-page/index.html
- UI/login-page/style.css
A fresh login page with neumorphism outlook.
> Adding Login Page based on neumorphism

- C++/Data_Structures/linked_list_implementation.cpp
I have added linked-list implementation in C++.
> Added linked list implementation in C++

- LeetCode Problems/C++/sortColors.cpp
Hey, I am a Hacktoberfest'21 participant.
I have created a solution of Leetcode Problem [Sort Colors](https://leetcode.com/problems/sort-colors/).
Kindly review it.
> sortColors

- LeetCode Problems/C++/84_Largest_Rectangle_in_Histogram.cpp
link to the question: https://leetcode.com/problems/largest-rectangle-in-histogram/
> Added solution to leetcode problem Largest Rectangle in Histogram

- C++/Data_Structures/Fenwick Tree/Fenwick Tree Template.cpp
- C++/Data_Structures/Sparse Table/Sparse Table Template.cpp
Added templates for Fenwick Tree and Sparse Table
> Add Sparse Table and Fenwick Tree templates

- AtCoder Dp Series/A-Frog1.cpp
- AtCoder Dp Series/B-Frog2.cpp
- AtCoder Dp Series/C-Vacation.cpp
- AtCoder Dp Series/D-Knapsack1.cpp
- CodeForces Problems/455A.cpp
> Added problem 455A (Boredom)

- Python/display_sum_of_first_even_n_numbers.py
- Python/displayoddnumbers.py
- Python/factorial_of_num_using_function.py
- Python/simple_calculator.py
added some simple python programs
> added files

- Java HackerRank/Data Structures/Java 1D Array/Array.java
> 1D array solution hackerrank

- C++/Data_Structures/Searching/FibonacciSearch.cpp
- C++/Data_Structures/Searching/JumpSearch.cpp
- C++/Data_Structures/Searching/linearSearch.cpp
i have added Fibonacci search, Jump Search and Linear Search programs in c++ language.
> Added more Searching Algorithms

- C++/Data_Structures/sorting/RadixSort.cpp
i have added radix sort algorithm in the Sorting Algorithm folder.
> Added Radix Sort Algorithm 

- share work
i am that only who contacted you on whatsapp from nasa app challenge
> showed my project

- share work
Reverts sudip-mondal-2002/HactoberFest21#120
> Revert "showed my project"

- LeetCode Problems/Java/BasicCalculator.java
file is in HactoberFest21/LeetCode Problems/Java/
file name BasicCalculator.java
> created a leef code solution

- Python/currency converter.py
> Create currency converter.py

- C++/Data_Structures/Maximum Frequency in a sequence.cpp
Program of Maximum Frequency in a sequence
> Maximum Frequency in a sequence.cpp

- CSES Solutions/Range Queries/dynamic_range_minimum_queries.cpp
- CSES Solutions/Range Queries/dynamic_range_sum_queries.cpp
- CSES Solutions/Range Queries/hotel_queries.cpp
- CSES Solutions/Range Queries/range_update_queries.cpp
- CSES Solutions/Range Queries/range_xor_queries.cpp
- CSES Solutions/Range Queries/static_range_minimum_queries.cpp
- CSES Solutions/Range Queries/static_range_sum_queries.cpp
Added solutions to many cses range query questions.
> CSES Questions Solutions

- Python/pronic_number.py
> Added Pronic Number Program

- C++/Recursion/sumof_square.cpp
Hi,
Please accept my PR and follow me on [https://github.com/Dashminder-Singh](url)
> add sum of first N square numbers

- LeetCode Problems/C++/Factorials_of_a_large_number.cpp
Added a solution code in c++ language for the question "Fcatorials of a large number".
>  Factorials of a large number

- CSES Solutions/cses_two_knights.cpp
added "Two Knights" cses problem solution in "CSES Solution" folder.
> Added cses_two_knights.cpp file in CSES Solutions

- Backtracking/N Queen Problem.c
- Backtracking/Rat in maze.c
- Backtracking/Subset Sum.c
I have added 3 backtracking problems.
1. Rat in maze
2. N-Queen Problem
3. Subset Sum Problem
> Added Backtracking Problems

- Python/encyclopedia.py
- Python/piechart.py
Program to print encyclopedia of given Word
> Encyclopedia of given Word

- C++/ToweOfHanoi.cpp
Please accept my PR under the label hacktoberfest-accepted .Thank you :)
> Added Tower of Hanoi

- Python/wumpus_world.py
Wumpus World Problem in Artificial Intelligence using Python
> Wumpus World Problem

- LeetCode Problems/C++/Binary Tree_Postorder_Traversal.cpp
added Binary Tree_Postorder_Traversal.cpp in Leetcode C++ folder
> added Binary Tree_Postorder_Traversal.cpp

- CodeForces Problems/687-A.cpp
> Added NP Hard Problem

- LeetCode Problems/C++/Merge In Between Linked Lists.cpp
Here I have provided a detailed solution to the leetcode problem 1669. With all the comments and the final running solution, one may find it useful looking through it and excelling in DSA.
> 1669. Merge In Between Linked Lists (C++)

- C++/Data_Structures/queue/Insert_delete_circular_queue.cpp
C++ program for insertion and deletion in Circular Queue
> Insert_delete_circular_queue.cpp

- Weather app_rtewari056/index.html
- Weather app_rtewari056/script.js
- Weather app_rtewari056/style.css
A simple, weather app written in HTML, CSS, and JavaScript. It gathers data from OpenWeatherMap, via their public API.
> Weather app by Rohit

- Python/printRouter.py
A new pattern, for beginners and how new computers adopt different symbols and emojis.
A good example of justifying strings according to the character space in terminal
> Print router(box) pattern with special characters

- DSA implementation using C/CircularQueue.c
- DSA implementation using C/DoublyLinkedList.c
- DSA implementation using C/PolynomialCalculation.c
- DSA implementation using C/Queue from stack.c
- DSA implementation using C/SingleLinkedList.c
- DSA implementation using C/Stacks.c
- DSA implementation using C/readme.md
- DSA implementation using C/sparsematrix.c
I have added several Data Structures - Stacks, Queues and Linked List and there related problems, please accept this and all hacktoberfest accepted tag!
> DSA implementation using C

- CODECHEF/Array Rotation Returns.cpp
In this, I have provided an elegant solution to the problem that appeared in July Lunchtime 2021 Div-3 (Problem - 4). Here's the link to the problem - https://www.codechef.com/LTIME98C/problems/ARRT/
I would encourage you to try this on your own for the first time and then go through the solution.
> Array Rotation Returns (Problem Code: ARRT)

- LeetCode Problems/Container With Most Water.py
> Container with most Water(medium)

- Vanilla-JavaScript-Calculator_rtewari056/index.html
- Vanilla-JavaScript-Calculator_rtewari056/script.js
- Vanilla-JavaScript-Calculator_rtewari056/styles.css
Calculator written in HTML, CSS and, Vanilla JavaScript.
> Added vanilla js calculator

- CodeForces Problems/1490-D.cpp
- CodeForces Problems/1560-D.cpp
These are the solutions of some good questions in codeforces. Please review my PR.
> Solutions of Codeforces problems

- LeetCode Problems/C++/Rabbits in Forest.cpp
This is a great problem for practising hashing as a concept. Here's the link - https://leetcode.com/problems/rabbits-in-forest/
Happy Coding!
> 781. Rabbits in Forest

- LeetCode Problems/C++/Remove Duplicates from Sorted List II.cpp
This is a problem for Linked Lists. Here's the link - https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/
A detailed solution has been provided that is easy to understand. 
Happy coding :-)
> 82. Remove Duplicates from Sorted List II

- C++/Even fibonacci.cpp
> Create Even fibonacci.cpp

- GfgTrack/Bits.cpp
- GfgTrack/Mathematics.cpp
- GfgTrack/Recursion.cpp
- GfgTrack/arrays.cpp
I added my cpp files containing important algorithms and gfg problem solution from gfg self pased dsa course.
> Added important algorithms from gfg dsa course

- C++/prims.cpp
> Added Path Algorithm "Prims Algorithm"

- LeetCode Problems/Python/minDelSum.py
Problem: 712. Minimum ASCII Delete Sum for Two Strings
Given two strings s1 and s2, return the lowest ASCII 
sum of deleted characters to make two strings equal.
Platform: LeetCode
Link: https://leetcode.com/problems/minimum-ascii-delete-sum-for-two-strings/
Performance: 85 % faster, 75 % less memory (relative)
Easy to read
> Minimum ASCII Delete Sum for Two Strings

- LeetCode Problems/Java/Moore's voting algorithm.java
With time complexity O(n) and space complexity O(1), moore's voting algorithm is best suited algorithm for this problem.
> Moore's voting algorithm

- C++/Power of three
Question ask to find that if the given number is of power of three or not .
> Create Power of three

- LeetCode Problems/C++/9.Palindrome_Number.cpp
In this PR, I have added a solution to the LeetCode problem **9. Palindrome Number**  in C++ language.
> Added Palindrome Number [LeetCode]

- C++/Recursion/palindrome.cpp
Just updated the the code by keeping mind time and space efficiency. For begineers it's easy to understand  and no need a complex keywords to confuse them.
> Updated palindrome.cpp

- CODECHEF/Beautiful Pairs.cpp
A problem from the July Lunchtime 2021 Div 3 (Problem number -3)  Here's the link -> https://www.codechef.com/LTIME98C/problems/BUTYPAIR
A clear and elegant solution for the same. Happy Coding
> Beautiful Pairs (Problem Code: BUTYPAIR)

- C++/Data_Structures/SieveOfEratosthenes.cpp
find all prime with in a range
> SieveOfEratosthenes.cpp

- C++/Data_Structures/merge_sort_in_linkedL/doublyll.cpp
- C++/Data_Structures/merge_sort_in_linkedL/mergeTwoSort.cpp
- here i convert merge sort algo to work with linkedlist
- i use doubly linked list 
- please accept it with a label hactober-accepted
-
> merge sort in linked list

- LeetCode Problems/Java/136_ Single_Number.java
- LeetCode Problems/Java/Merge_sorted_array.java
Simple solution to problem number 136 on leetcode in java.
> Solution to problem number 136 in java.

- Python/add_number_LL.py
Leetcode medium, with driver code and support functions
> Add two numbers represented as Linked List
